# -*- coding: utf-8 -*-
"""NumpyPandasDatavisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bIeNtyz_T0qPYYm9y_nBnLwx5IAl4H2

1. NumPy – Student Marks Analysis
"""

#1. NumPy – Student Marks Analysis
import numpy as np

marks = np.array([85, 72, 90, 65, 78, 88, 55, 92, 70, 81])

total = np.sum(marks)
average = np.mean(marks)
highest = np.max(marks)
lowest = np.min(marks)
above_75 = marks[marks > 75]

print("Marks:", marks)
print("Total Marks:", total)
print("Average Marks:", average)
print("Highest Marks:", highest)
print("Lowest Marks:", lowest)
print("Marks greater than 75:", above_75)

"""2. NumPy – Temperature Analysis"""

import numpy as np

temperature = np.array([28, 32, 31, 29, 34, 27, 33])

average = np.mean(temperature)
highest = np.max(temperature)
lowest = np.min(temperature)
above_30 = temperature[temperature > 30]

updated_temperature = temperature + 2

print("Temperatures:", temperature)
print("Average Temperature:", average)
print("Highest Temperature:", highest)
print("Lowest Temperature:", lowest)
print("Temperatures above 30°C:", above_30)
print("Updated Temperatures:", updated_temperature)

"""3. Pandas – Student Performance DataFrame"""

import pandas as pd

data = {
    "Name": ["Arun", "Priya", "Rahul", "Meena", "Kavin", "Divya", "Ravi", "Anu"],
    "Department": ["IT", "CSE", "IT", "ECE", "CSE", "IT", "ECE", "CSE"],
    "Marks": [85, 72, 90, 65, 78, 88, 55, 92],
    "Attendance": [90, 85, 95, 75, 82, 78, 88, 96]
}

df = pd.DataFrame(data)

print("First 5 Students:")
print(df.head())

print("\nAverage Marks:", df["Marks"].mean())

print("\nStudents who scored more than 75:")
print(df[df["Marks"] > 75])

print("\nStudents with attendance below 80%:")
print(df[df["Attendance"] < 80])

print("\nStudents sorted by marks:")
print(df.sort_values("Marks"))

"""4. Pandas – Product Sales Analysis"""

import pandas as pd

data = {
    "Product Name": ["Laptop", "Mobile", "Headphones", "Keyboard", "Mouse"],
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Accessories"],
    "Price": [50000, 20000, 2000, 1500, 800],
    "Quantity Sold": [10, 35, 60, 70, 90]
}

df = pd.DataFrame(data)

df["Total Sales"] = df["Price"] * df["Quantity Sold"]

print("Product Sales Data:")
print(df)

print("\nProduct with Highest Sales:")
print(df.loc[df["Total Sales"].idxmax()])

print("\nAverage Product Price:", df["Price"].mean())

print("\nProducts with Quantity Sold greater than 50:")
print(df[df["Quantity Sold"] > 50])

print("\nProducts sorted by Total Sales:")
print(df.sort_values("Total Sales"))

"""5. Data Visualization – Monthly Sales"""

import matplotlib.pyplot as plt

months = ["January", "February", "March", "April", "May", "June"]
sales = [25000, 30000, 28000, 35000, 40000, 38000]

plt.plot(months, sales, marker="o", label="Monthly Sales")
plt.title("Monthly Sales")
plt.xlabel("Months")
plt.ylabel("Sales Amount")
plt.legend()
plt.show()

plt.bar(months, sales, label="Monthly Sales")
plt.title("Monthly Sales Comparison")
plt.xlabel("Months")
plt.ylabel("Sales Amount")
plt.legend()
plt.show()

"""6. Data Visualization – Student Marks"""

import matplotlib.pyplot as plt

students = ["Arun", "Priya", "Rahul", "Meena", "Kavin",
            "Divya", "Ravi", "Anu", "Vijay", "Sara"]

marks = [85, 72, 90, 65, 78, 88, 35, 92, 55, 45]

plt.bar(students, marks)
plt.title("Student Marks in Python")
plt.xlabel("Students")
plt.ylabel("Marks")
plt.xticks(rotation=45)
plt.show()

excellent = 0
good = 0
average = 0
needs_improvement = 0

for mark in marks:
    if mark >= 80:
        excellent += 1
    elif mark >= 60:
        good += 1
    elif mark >= 40:
        average += 1
    else:
        needs_improvement += 1

categories = ["Excellent", "Good", "Average", "Needs Improvement"]
counts = [excellent, good, average, needs_improvement]

plt.pie(counts, labels=categories, autopct="%1.1f%%")
plt.title("Student Performance Distribution")
plt.show()